### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by drewnyc** [ridwanskaterock/cicool#27] opened 2017-02-18 23:46 UTC
I am trying to install for the first time and get:

Not Found

The requested URL /wizzard/setup was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Any help would be appreciated.  Many thanks,

Drew Hart

MySQL - 5.6.35
PHP - 5.5
Thanks.

**Comment by ridwanskaterock** [comment] 2017-02-20 02:13
if you add index.php on the url, it's run smothly ? 
example  /wizzard/setup/index.php

if run smothly you must active mod_rewrite in apache

thanks

**Comment by drewnyc** [comment] 2017-02-20 18:03
Still doens't work - I get this error:

Not Found

The requested URL /wizzard/setup/index.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I did check that mbstring, mod_rewrite, etc., was all working and they are...Thanks,

Drew

**Comment by drewnyc** [comment] 2017-02-20 18:09
Actually, I got it to work (partially) by installing in a sub-directory    domain.com/cicool.  I had it installed in the root, just domain.com, and it wasn't working.  The thing is, that I want it in the root, and not in domain.com/cicool.  However, even in the subdirectory, I get stuck at step 3 after I enter the database info, when I click next, I get the following error (again after step 3):


An Error Was Encountered

The action you have requested is not allowed.

Any help would be appreciated.  Thanks,

Drew

**Comment by drewnyc** [comment] 2017-02-22 22:15
Just wondered if you had any advice - I would really like to get this working.  Thanks,

**Comment by ridwanskaterock** [comment] 2017-02-23 07:43
if in step 3 you still get the same message when the configuration database?

you try to refresh the page :)

**Comment by ridwanskaterock** [comment] 2017-02-23 07:45
whether the problem has been completed?

i will close this issue :) thanks

**Comment by drewnyc** [comment] 2017-02-23 22:23
No it's not completed - I can't get it to work - I have been waiting for some help!  Thanks,

Drew

**Comment by ridwanskaterock** [comment] 2017-02-24 01:57
sorry I think you can already solve them, could I ask for credentials ftp to your server so that I can test it :)

I will help you to walk normally

**Comment by drewnyc** [comment] 2017-03-01 00:26
can I have your email - I don't want to post them publicly.  Thanks,

**Comment by drewnyc** [comment] 2017-03-01 00:27
or you can email me at drewehart@gmail.com

**Comment by CovapDigital** [comment] 2017-03-23 13:24
Hi, i have the same issue that drewnyc. 

An Error Was Encountered
The action you have requested is not allowed.

Any help?

Thanks

**Comment by ridwanskaterock** [comment] 2017-03-27 08:48
can explain what the server and use? 

thanks

**Comment by CovapDigital** [comment] 2017-03-27 14:04
Hi, thanks for your response.

I have experience in codeigniter and I have been able to review the Controler Wizard. I tried the installation on local server and there was no problem. However when trying to install on real server, I always get the operation message not allowed.

I'm pretty sure the problem may be in creating the database.php and site.php files, the first thing I've tried is to give 777 permissions to the folders that include them. However, in the first step of the installation all permissions are displayed in green.

**Comment by CovapDigital** [comment] 2017-03-28 09:37
Hello,

thanks for your answer. Please excuse me for explaining my case so poorly.

Finally I managed to run the system on a real server. As expected some kind of permission was preventing the execution.

In my case, the problem is an 'open base dir' constraint. The system is configured to save sessions to the file system and my server has restricted access to the default session folder.

I have modified the path for storing sessions to a directory on the same level as the system and everything has worked correctly.

The problem of the installation I did not know how to solve it, I have studied the steps of the wizard and I have executed them manually (create database.php, create site.php and insert the user into the database)

If this can help, if you have problems, you must modify the environment of CodeIgniter to development to show the errors.

**Comment by ridwanskaterock** [comment] 2017-03-28 13:26
yes actually I previously showed a problem when there is an error,

but the envanto mereject and would not allow it,

so if your problem has been completed?

thanks

**Comment by CovapDigital** [comment] 2017-03-28 13:27
Yes, my problem is solved. It was fundamental to activate the codeigniter development mode. Once the errors were displayed, it was all about debugging the restrictions.

Thks for your support.

**Comment by ridwanskaterock** [comment] 2017-03-28 13:29
yes same as I would develop a better future :) thanks

**Closed by ridwanskaterock** 2017-03-28 13:29 UTC

**Comment by johnfelipe** [comment] 2018-12-18 06:12
> codeigniter development mode

how can activate  codeigniter development mode i have nginx not apache

**Comment by ridwanskaterock** [comment] 2018-12-18 09:02
Hi. You can change environtment to development on index.php
